### PR TITLE
bump versions (of Scala, Akka, Akka-Http, sbt, JDK)

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
note that Scala 2.13.0-M3 isn't worth building for anymore, but we can't add M5 yet instead because your dependencies haven't published.

**Comment by SethTisue** [comment]
@jrudolph does the test failure mean that akka-http needs to be rebuilt using Scala 2.12.8?

**Comment by lomigmegard** [comment]
@SethTisue Thanks for the PR, the error is indeed pretty strange!

For the record, the actual compilation error is only there with `Openjdk11 + Scala 2.12.8`, all other combination of `Java8/Scala2.11` are working.
```
[error] /home/travis/build/lomigmegard/akka-http-cors/akka-http-cors-example/src/main/java/ch/megard/akka/http/cors/javadsl/CorsServer.java:29:1: reference to get is ambiguous
[error]   both method get(akka.actor.ActorSystem) in akka.http.javadsl.Http and method get(akka.actor.ActorSystem) in akka.http.javadsl.Http match
[error]         final Http http = Http.get(system);
```

When the root cause is found and this PR merged, I can quickly cut a new release.

**Comment by lomigmegard** [comment]
Looks related to https://github.com/akka/akka-http/issues/2211

@SethTisue I updated the code with a workaround (https://github.com/lomigmegard/akka-http-cors/commit/678e181a8acc07acbee9befc065a58d258f1ad44) to this issue. Please rebase on master, it should work now.

**Pull request merged**
