### PR TITLE
Support `Origin: null` in simple/actual requests

### LINKED ISSUE #31: Support `Origin: null` in simple/actual requests
Follow-up to the question raised in #30 by @AlessandroEmm.

If the CORS directive supports `Origin: null` in simple/actual requests, it will probably require breaking changes on `CorsRejection`.

Also, it will directly go against the recommendation to avoid returning [`Access-Control-Allow-Origin: null`](https://w3c.github.io/webappsec-cors-for-developers/#avoid-returning-access-control-allow-origin-null). I don't know how big of a problem it is in practice.

First thing is to look at other implementations to see how they handle this case.

### PR DESCRIPTION
**Pull request by lomigmegard**
Fix #31.

### CODE REVIEW

**Comment by ShuiShengYe** [comment]
@lomigmegard I have this problem that "Origin: null". I used your new code, but it didn't work.

**Comment by lomigmegard** [comment]
@ShuiShengYe which version did you use? this PR is not merged yet.
I just released the version `0.3.0-SNAPSHOT` on Sonatype Snapshot repository, which contains these changes.

(`resolvers += Resolver.sonatypeRepo("snapshots")`

**Comment by ShuiShengYe** [comment]
@lomigmegard I use the version 0.3.0-SNAPSHOT. and publish it to local.

**Comment by lomigmegard** [comment]
@ShuiShengYe What error did you get? `Origin: null` is a very special case that should not occur normally.

**Pull request merged**
